services:
  _defaults:
    autowire: true
    autoconfigure: true

  designerei\ContaoNewsContentElementBridgeBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,DependencyInjection,ContaoNewsContentElementBridgeBundle.php}